# Generated by Django 2.1.15 on 2020-06-16 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_user_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='投稿者名')),
                ('contents', models.CharField(blank=True, max_length=255, verbose_name='欲しいもの')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fav', models.IntegerField(verbose_name='いいね数')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
