# Generated by Django 2.1.15 on 2020-06-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Work',
            name='title',
            field=models.CharField(max_length=255, verbose_name='タイトル'),
        ),
    ]
